### ISSUE TITLE
Develop single profile layout

### ISSUE THREAD

**Issue by FrancesCoronel** [Latina-Dev/latina-dev#19]
## Basic Fields

- Picture
- Name
- Current Affiliation/Title
- Level (Student, IC, Leader)

## Links

- LinkedIn
- Twitter
- GitHub
- Personal Website

## Additional Options

- Country or countries of origin (e.g. Peruvian)
- Available for speaking
- Available for mentoring
- Actively seeking new opportunities

**Comment by latinadeveloper** [comment]
I have two mockups, each with 2 versions. 
On some I made comments since I don't have icons. 

The frame has the title of what it is.
