### ISSUE TITLE
Request open source sponsorship from Vercel

### ISSUE THREAD

**Issue by FrancesCoronel** [Latina-Dev/latina-dev#22]
## Why

Only the pro plan allows me to add collaborators to maintain and configure our project in Vercel.

But more importantly, you can only get unlimited reviewers on the Pro plan where we view the UI with team comments on Previews which is a feature that is very useful for us.

## Requirements

- [x] The project should be non-commercial.
- [x] The project should be open source.
- [x] The project's usage should fall under [fair use](https://vercel.com/docs/concepts/limits/fair-use-policy).
- [x] A Vercel banner should be present in the footer of each site page.
- [x] A Vercel banner should be present in the source repository's README.md file.
- [x] All links back to Vercel should use a UTM tag with the format: ?utm_source=[team-name]&utm_campaign=oss.

https://vercel.com/guides/can-vercel-sponsor-my-open-source-project

**Comment by FrancesCoronel** [comment]
@EllaCodes4 I can take care of the README update 

![Vercel](https://images.ctfassets.net/e5382hct74si/78Olo8EZRdUlcDUFQvnzG7/fa4cdb6dc04c40fceac194134788a0e2/1618983297-powered-by-vercel.svg)

The link would be `https://vercel.com?utm_source=latina-dev&utm_campaign=oss`

**Comment by EllaCodes4** [comment]
@FrancesCoronel Done! Check it out and LMK if we're ready to merge!
