### ISSUE TITLE
Labeler github action failure follow up

### ISSUE THREAD

**Issue by latinadeveloper** [Latina-Dev/latina-dev#31]
## Describe the bug

Labeler github action is running now, but the labeler.yml file that has the labels has incorrect syntax. 

## To Reproduce

1. Create a PR and submit
2. See syntax 
screenshot 
<img width="772" alt="image" src="https://user-images.githubusercontent.com/19174332/236537690-34eb39cc-a424-4363-bc67-171100263fdb.png">

**Comment by FrancesCoronel** [comment]
@latinadeveloper This should be good to go
