### ISSUE TITLE
Explore and explain what is Latina > Build It

### ISSUE THREAD

**Issue by latinadeveloper** [Latina-Dev/latina-dev#40]
## Is your feature request related to a problem?

Have an information page about What does Latina mean. 

## Describe the solution you'd like
Discover a way to explain what a Latina is. 
Do we want to create an About page, What is latina page? 

Figure out the best way to talk about what a Latina is whether it is to do an about page, or a what is latina page?

Gather information and write the paragraph/s on this. 
Create page design to add this to and add curated content.

**Comment by FrancesCoronel** [comment]
# What is a Latina?

The term "Latina" generally applies to women or individuals who are of Latin American or Hispanic descent, regardless of their country of birth or current residence. It encompasses people from diverse backgrounds, including but not limited to countries such as Mexico, Puerto Rico, Cuba, the Dominican Republic, Colombia, Peru, and many others.

Being Latina involves embracing and celebrating the language, customs, traditions, and cultural heritage associated with Latin American countries. It can include speaking Spanish or Portuguese, participating in cultural festivals and events, enjoying Latin American cuisine, and maintaining connections with family and community.

It is important to note that the experiences and identities within the Latina community are incredibly diverse. Latinas come from various racial, ethnic, and socioeconomic backgrounds, and their individual experiences and perspectives may differ greatly. Therefore, it is essential to recognize and respect the unique identities and backgrounds of Latinas, as well as to avoid generalizations or assumptions about their experiences.

**Possibly expand one day an ‘about [[latina.dev](http://latina.dev/)](http://latina.dev)’ and what it means as an open source project.**

As an open source project led by Latina software engineers, our mission is to empower Latinas in the tech industry and foster an inclusive and supportive community. We recognize the importance of being a Latina and how it intertwines with our expertise in software engineering and open source development.

Being a Latina within the context of our open source project signifies the fusion of our Latin American heritage with our passion for technology and collaboration. It embodies our commitment to leveraging open source principles to drive innovation, create impactful solutions, and bridge the diversity gap in the tech world.

We take great pride in embracing our cultural identity while actively contributing to the open source community. As Latina software engineers, we bring diverse perspectives, unique experiences, and novel approaches to problem-solving. We challenge stereotypes, dismantle barriers, and demonstrate the incredible talent and potential that exists within our community.

Through our open source project, we provide a platform for Latina software engineers to collaborate, share knowledge, and advance their skills. We believe in the power of mentorship, peer support, and skill-building initiatives to empower Latinas and cultivate their leadership abilities in the tech industry.

Being a Latina software engineer in an open source project embodies resilience, determination, and the drive to make a lasting impact. It signifies using our technical expertise to drive positive change, promote inclusivity, and create opportunities for underrepresented individuals. We strive to inspire future generations of Latinas to pursue careers in technology and contribute to the open source ecosystem.

In essence, as an open source project led by Latina software engineers, we embrace our cultural heritage while making significant contributions to the world of technology. We are committed to empowering Latinas, fostering diversity, and building an inclusive tech community. Together, we are reshaping the narrative and opening doors for Latinas to thrive in the open source and tech space.

**Comment by FrancesCoronel** [comment]
Shared the description that was put in Notion

**Comment by FrancesCoronel** [comment]
I think best path would be to have this be a section on the about page

**Comment by latinadeveloper** [comment]
> I think best path would be to have this be a section on the about page

So we have an About Us Section. I believe having another tab with 'About' and then an edited description of what is above. 
Or would this also be an opportunity to move the About Us part also from the main page?

**Comment by FrancesCoronel** [comment]
@latinadeveloper Yes I think it would make sense to separate out About Page into its own page and then add a section for this there

There can still be a shorter snippet on the homepage that uses some of the same text that can be found on the about page

**Comment by EllaCodes4** [comment]
Thanks so much for putting this together, @latinadeveloper! Very informative! 
An About tab and page can easily be added and I'd be happy to support you with this! 

I agree with @FrancesCoronel about keeping the "About" snippet on the homepage and then adding to it on the "About" page!
