### ISSUE TITLE
Heading title/logo

### ISSUE THREAD

**Issue by latinadeveloper** [Latina-Dev/latina-dev#45]
Issue: 
Most websites have the name of the organization and logo at the top, usually where the heading goes. 

Task: 
Investigate if this is wanted.
Create a design for it, desktop & mobile. 
Implement.

**Comment by EllaCodes4** [comment]
Initial design templates (see 02_LatinaDev_About nav bar): https://www.figma.com/file/8YMOVXRssxvxwITCzsRaIO/LatinaDev-Design-Templates?type=design&mode=design
