### ISSUE TITLE
Refresh styling

### ISSUE THREAD

**Issue by EllaCodes4** [Latina-Dev/latina-dev#81]
- Replace all custom CSS with Tailwind classes (where possible)
- Right now we have a bunch of custom CSS, and we want to just rely on tailwind classes if possible

**Comment by vinay-nb** [comment]
Hi @EllaCodes4  
I would like to work on this issue

**Comment by EllaCodes4** [comment]
> Hi @EllaCodes4 I would like to work on this issue

Hi @vinay-nb! Thank you for your interest in contributing! We'd love your support as we grow our community and directory! How did you hear about the Latina Dev community?!

**Comment by FrancesCoronel** [comment]
@vinay-nb I went ahead and assigned this issue to you - let us know if you have any questions!

**Comment by FrancesCoronel** [comment]
@vinay-nb Since we haven't heard anything from you, I'm going to have someone else take a stab at this! If you're interested in working on this again, just let us know and we can follow up. 😄

**Comment by Jasminvillatoro** [comment]
✅

**Comment by Jasminvillatoro** [comment]
I submitted a PR
