### ISSUE TITLE
Add 50 Latina software enginners who have already given consent 

### ISSUE THREAD

**Issue by EllaCodes4** [Latina-Dev/latina-dev#82]
They are listed here: https://www.notion.so/francescoronel/Latina-Dev-Notion-Hub-11e125c82da3410ca014cd479319b172

Our goal is to feature at least 50 Latinas by 8/24! 
Current count: 39
We can do it! Teamwork makes the dreamwork!

**Comment by FrancesCoronel** [comment]
We did it!

cc @EllaCodes4
